training_cfg:
  device: "cuda"
  batch_size: 256
  epochs: 30
  epoch_size: 2560
  n_iter_log: 10
  seed: 0

data_cfg:
  path: "./data/"
  dim_image: 64

generator_cfg:
  n_channels: 512
  dim_z: 32
  n_layers_z: 4
  n_layers_block: 3
  n_noise: 10
  lr: 1.0e-4
  betas: [0.5, 0.5]
  gamma: 0.1
  running_avg_factor: 0.9
  weight_avg_factor: 0.5
  dropout: 0.3

discriminator_cfg:
  n_channels: 12
  n_layers_d_block: 5
  lr: 1.0e-4
  betas: [0.5, 0.99]
  gamma: 0.1
  running_avg_factor: 0.9
  weight_avg_factor: 0.5
  dropout: 0.3
